// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'ProductBridge',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started',
            },
          ],
        },
        {
          type: 'category',
          label: 'API Documentation',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'api-docs',
            },
          ],
        },
        {
          type: 'autogenerated',
          dirName: 'configuration-and-settings',
        },
      ],
    },
  ],

  faqSidebar: [
    {
      type: 'autogenerated',
      dirName: 'FAQ',
    },
  ],
};

export default sidebars;