name: Vale Style Guide Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vale:
    name: Lint Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          files: 'docs'
          level: suggestion         # Valid input for alert level
          fail_on_error: false      # Prevents red cross when suggestions are found
          reporter: github-pr-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
