name: Vale Style Guide Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # <-- Allows you to manually click "Run Workflow" on GitHub!

jobs:
  vale:
    name: Lint Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          styles: .vale.ini
          files: 'docs'
          minAlertLevel: suggestion
          reporter: github-pr-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}